export const menu = [
  {
    id: 1,
    title: 'Buttermilk Pancakes',
    category: 'breakfast',
    price: 13.79,
    img: './images/food/1.jpeg',
    description: `A pancake is a flat cake, often thin and round, prepared from a starch-based batter that may contain eggs, milk and butter and cooked on a frying pan`,
  },
  {
    id: 2,
    title: 'Traditional English Breakfast',
    category: 'breakfast',
    price: 18.99,
    img: './images/food/2.jpeg',
    description: `The full English breakfast consists of fried eggs, sausages, back bacon, tomatoes, mushrooms, fried bread and often a slice of white or black pudding`,
  },
  {
    id: 3,
    title: 'Peach Crisp Yogurt Bowls',
    category: 'breakfast',
    price: 15.69,
    img: './images/food/3.jpeg',
    description: `Bowls of creamy vanilla yogurt, topped with fresh, juicy roasted peaches`,
  },
  {
    id: 4,
    title: 'Pasta Carbonara',
    category: 'lunch',
    price: 17.99,
    img: './images/food/4.jpeg',
    description: `Carbonara is an Italian pasta dish from Rome made with eggs, hard cheese, cured pork, and black pepper`,
  },
  {
    id: 5,
    title: 'Pizza Margherita',
    category: 'lunch',
    price: 21.99,
    img: './images/food/5.jpeg',
    description: `Pizza Margherita is a typical Neapolitan pizza, made with San Marzano tomatoes, mozzarella cheese, fresh basil, salt, and extra-virgin olive oil`,
  },
  {
    id: 6,
    title: 'Avocado Bowl',
    category: 'lunch',
    price: 16.99,
    img: './images/food/6.jpeg',
    description: `Healthy bowl with avocado, eggs, vegetables. Add your favourite whole grains`,
  },
  {
    id: 7,
    title: 'Crepes with Berries',
    category: 'dessert',
    price: 12.99,
    img: './images/food/7.jpeg',
    description: `Crepes is a type of very thin pancake. Served with cream and berries`,
  },
  {
    id: 8,
    title: 'Chocolate Cake',
    category: 'dessert',
    price: 9.69,
    img: './images/food/8.jpeg',
    description: `Chocolate cake is a cake flavored with melted chocolate, cocoa powder`,
  },
  {
    id: 9,
    title: 'Cinnamon Roll',
    category: 'dessert',
    price: 7.99,
    img: './images/food/9.jpeg',
    description: `A cinnamon roll consists of a rolled sheet of yeast-leavened dough onto which a cinnamon and sugar mixture`,
  },
];